<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>29a40305-a22a-4b87-b19a-18abd31c5a56</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.6" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.6" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ArtifactStore.Auth.Domain\ArtifactStore.Auth.Domain.csproj" />
      <ProjectReference Include="..\ArtifactStore.Auth.Application\ArtifactStore.Auth.Application.csproj" />
      <ProjectReference Include="..\ArtifactStore.Auth.Infrastructure\ArtifactStore.Auth.Infrastructure.csproj" />
    </ItemGroup>

</Project>
