<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ArtifactStore.Application\ArtifactStore.Application.csproj" />
      <ProjectReference Include="..\ArtifactStore.Domain\ArtifactStore.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
      <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.5" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.6" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.6" />
      <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Repositories\Mongo\" />
    </ItemGroup>

</Project>
