@startuml

|Пользователь|
start

|Пользователь|
:Выбирает товар для покупки;
:Делает запрос на покупку;

|Frontend|
:Формирует API-запрос;
:Отправляет API-запрос;

|Middleware|
:Отправляет запрос на проверку 
по правам доступа;
|AuthService|
if (Права доступа подходящие) then (Да)
    :Ищется подходящий контроллер;
    if (Контроллер найден) then (Да)
        |StoreController|
        :Запуск выполнения покупки;
        |StoreService|
        :Выполнение покупки;
        |PurchaseService|
        :Получание входных данных;
        |StoreProcedureRepository|
        :Запуск хранимой процедуры;
        |Frontend|
        :Формирование сообщения об
        успехе выполнения операции;
    else (Нет)
        |Frontend|
        :Формирование сообщения об
        ошибке на сервере;

        stop
    endif
else (Нет)
    |Frontend|
    :Формирование сообщения об
    ошибке по правам доступа;

    stop
endif

end
@enduml