@startuml

|Администратор|
start

|Администратор|
:Делает запрос на отображение
артефактов на продаже;

|Frontend|
:Формирует API-запрос;
:Отправляет API-запрос;

|Middleware|
:Отправляет запрос на проверку 
по правам доступа;
|AuthService|
if (Права доступа подходящие) then (Да)
    :Ищется подходящий контроллер;
    if (Контроллер найден) then (Да)
        |StoreController|
        :Запуск получения информации
        о продажах артефактов;
        |StoreService|
        :Получение информации о
        продажах артефактов;
        |Frontend|
        :Отображение информации;

        |Администратор|
        :Выбирает артефакт;
        :Делает запрос на удаление
        артефакта на продаже;

        |Frontend|
        :Формирует API-запрос;
        :Отправляет API-запрос;

        |Middleware|
        :Отправляет запрос на проверку 
        по правам доступа;
        |AuthService|
        if (Права доступа подходящие) then (Да)
            :Ищется подходящий контроллер;
            if (Контроллер найден) then (Да)
                |StoreController|
                :Запуск удаления информации
                о продаже артефакта;
                |StoreService|
                :Удаления информации
                о продаже артефакта;
                |StoreRepository|
                :Удаление;
                |Frontend|
                :Формирование сообщения об
                успехе выполнения операции;
            else (Нет)
                |Frontend|
                :Формирование сообщения об
                ошибке на сервере;

                stop
            endif
        else (Нет)
            |Frontend|
            :Формирование сообщения об
            ошибке по правам доступа;

            stop
        endif
    else (Нет)
        |Frontend|
        :Формирование сообщения об
        ошибке на сервере;

        stop
    endif
else (Нет)
    |Frontend|
    :Формирование сообщения об
    ошибке по правам доступа;

    stop
endif

end
@enduml