@startuml

|Администратор|
start
:Запрашивает информацию об артефактах на продаже
для мониторинга;

|Система|
:Отправляет запрос на получение информации;

|Хранилище|
:Получает информацию по запросу;

|Система|
:Визуализирует запрос в таблице;

|Администратор|
:Выбирает лот на удаление;
:Посылает информацию о лоте для удаления;

|Система|
:Отправляет запрос на удаление лота в магазине;

|Хранилище|
:Удаляет лот;

|Система|
:Визуализирует информацию об удалении лота;

end

@enduml