@startuml

|Пользователь|
start

:Просматривает магазин артефактов;
:Нажимает кнопку "Купить артефакт";

|Система|
:Получает данные желаемого артефакта и игрока;
:Запрашивает баланс с необходимой валютой;

|Хранилище|
:Ищет баланс;
:Отправляет информацию по запросу;

|Система|
:Запускает хранимую процедуру;

|Хранилище|
:Хранимая процедура выполняется;

|Система|
:Завершает транзакцию;

|Система|
:Формируется сообщение об операции;

end

@enduml