@startuml

|Модератор|
start

:Запрашивает информацию о странице транзакций
для мониторинга;

|Система|
:Отправляет запрос на получение информации;

|Хранилище|
:Получает информацию по запросу;

|Система|
:Визуализирует запрос в таблице;

end

@enduml